# -*- coding: utf-8 -*-
#
# This is a data migration, which loads into the CountryCode model.
#


from django.db import migrations


COUNTRY_CODES = [
    ("Andorra", "AD"),
    ("Palestinian Territory, Occupied", "PS"),
    ("Portugal", "PT"),
    ("Palau", "PW"),
    ("Paraguay", "PY"),
    ("Qatar", "QA"),
    ("Réunion", "RE"),
    ("Romania", "RO"),
    ("Serbia", "RS"),
    ("Russian Federation", "RU"),
    ("Rwanda", "RW"),
    ("Saudi Arabia", "SA"),
    ("Solomon Islands", "SB"),
    ("Seychelles", "SC"),
    ("Sudan", "SD"),
    ("Sweden", "SE"),
    ("Singapore", "SG"),
    ("Slovenia", "SI"),
    ("Svalbard and Jan Mayen", "SJ"),
    ("Slovakia", "SK"),
    ("Sierra Leone", "SL"),
    ("San Marino", "SM"),
    ("Senegal", "SN"),
    ("Suriname", "SR"),
    ("Sao Tome and Principe", "ST"),
    ("El Salvador", "SV"),
    ("Syrian Arab Republic", "SY"),
    ("Swaziland", "SZ"),
    ("Turks and Caicos Islands", "TC"),
    ("Chad", "TD"),
    ("French Southern Territories", "TF"),
    ("Somalia", "SO"),
    ("Togo", "TG"),
    ("Thailand", "TH"),
    ("Tajikistan", "TJ"),
    ("Tokelau", "TK"),
    ("Timor-leste", "TL"),
    ("Turkmenistan", "TM"),
    ("Tunisia", "TN"),
    ("Saint Helena", "SH"),
    ("Turkey", "TR"),
    ("Trinidad and Tobago", "TT"),
    ("Tuvalu", "TV"),
    ("Taiwan", "TW"),
    ("Tanzania, United Republic of", "TZ"),
    ("Ukraine", "UA"),
    ("United States Minor Outlying Islands", "UM"),
    ("United States of America", "US"),
    ("Uruguay", "UY"),
    ("Uzbekistan", "UZ"),
    ("Holy See (vatican City State)", "VA"),
    ("Saint Vincent and The Grenadines", "VC"),
    ("Venezuela, Bolivarian Republic of", "VE"),
    ("Virgin Islands, British", "VG"),
    ("Virgin Islands, U.s.", "VI"),
    ("Viet Nam", "VN"),
    ("Vanuatu", "VU"),
    ("Wallis and Futuna", "WF"),
    ("Uganda", "UG"),
    ("Tonga", "TO"),
    ("Central African Republic", "CF"),
    ("Congo", "CG"),
    ("Switzerland", "CH"),
    ("Cook Islands", "CK"),
    ("Chile", "CL"),
    ("China", "CN"),
    ("Colombia", "CO"),
    ("Costa Rica", "CR"),
    ("Cuba", "CU"),
    ("Cape Verde", "CV"),
    ("Christmas Island", "CX"),
    ("Cyprus", "CY"),
    ("Czech Republic", "CZ"),
    ("Germany", "DE"),
    ("Djibouti", "DJ"),
    ("Denmark", "DK"),
    ("Dominica", "DM"),
    ("Dominican Republic", "DO"),
    ("Algeria", "DZ"),
    ("Ecuador", "EC"),
    ("Estonia", "EE"),
    ("Egypt", "EG"),
    ("Western Sahara", "EH"),
    ("Eritrea", "ER"),
    ("Spain", "ES"),
    ("Ethiopia", "ET"),
    ("Finland", "FI"),
    ("Fiji", "FJ"),
    ("Falkland Islands (malvinas)", "FK"),
    ("Micronesia, Federated States of", "FM"),
    ("Faroe Islands", "FO"),
    ("France", "FR"),
    ("Gabon", "GA"),
    ("United Kingdom", "GB"),
    ("Grenada", "GD"),
    ("Georgia", "GE"),
    ("French Guiana", "GF"),
    ("Guernsey", "GG"),
    ("Cameroon", "CM"),
    ("Ghana", "GH"),
    ("Gibraltar", "GI"),
    ("Greenland", "GL"),
    ("Gambia", "GM"),
    ("Guinea", "GN"),
    ("Guadeloupe", "GP"),
    ("Equatorial Guinea", "GQ"),
    ("Côte D'ivoire", "CI"),
    ("Greece", "GR"),
    ("South Georgia and The South Sandwich Islands", "GS"),
    ("Guatemala", "GT"),
    ("Guam", "GU"),
    ("Guinea-bissau", "GW"),
    ("Guyana", "GY"),
    ("Hong Kong", "HK"),
    ("Heard Island and Mcdonald Islands", "HM"),
    ("Honduras", "HN"),
    ("Croatia", "HR"),
    ("Haiti", "HT"),
    ("Hungary", "HU"),
    ("Indonesia", "ID"),
    ("Ireland", "IE"),
    ("Israel", "IL"),
    ("Isle of Man", "IM"),
    ("India", "IN"),
    ("British Indian Ocean Territory", "IO"),
    ("Iraq", "IQ"),
    ("Iran", "IR"),
    ("Iceland", "IS"),
    ("Italy", "IT"),
    ("Jersey", "JE"),
    ("Jamaica", "JM"),
    ("Jordan", "JO"),
    ("Japan", "JP"),
    ("Kenya", "KE"),
    ("Kyrgyzstan", "KG"),
    ("Cambodia", "KH"),
    ("Kiribati", "KI"),
    ("Comoros", "KM"),
    ("Saint Kitts and Nevis", "KN"),
    ("Korea, Democratic People's Republic of", "KP"),
    ("Korea, Republic of", "KR"),
    ("Kuwait", "KW"),
    ("Cayman Islands", "KY"),
    ("Kazakhstan", "KZ"),
    ("Lao People's Democratic Republic", "LA"),
    ("Lebanon", "LB"),
    ("Saint Lucia", "LC"),
    ("Liechtenstein", "LI"),
    ("Sri Lanka", "LK"),
    ("Liberia", "LR"),
    ("Lesotho", "LS"),
    ("Lithuania", "LT"),
    ("Luxembourg", "LU"),
    ("Latvia", "LV"),
    ("Samoa", "WS"),
    ("Yemen", "YE"),
    ("Mayotte", "YT"),
    ("Zimbabwe", "ZW"),
    ("United Arab Emirates", "AE"),
    ("Afghanistan", "AF"),
    ("Antigua and Barbuda", "AG"),
    ("Anguilla", "AI"),
    ("Albania", "AL"),
    ("Armenia", "AM"),
    ("Netherlands Antilles", "AN"),
    ("Angola", "AO"),
    ("Antarctica", "AQ"),
    ("Argentina", "AR"),
    ("American Samoa", "AS"),
    ("Austria", "AT"),
    ("Australia", "AU"),
    ("Aruba", "AW"),
    ("Åland Islands", "AX"),
    ("Azerbaijan", "AZ"),
    ("Bosnia and Herzegovina", "BA"),
    ("Barbados", "BB"),
    ("Bangladesh", "BD"),
    ("Belgium", "BE"),
    ("Burkina Faso", "BF"),
    ("Bulgaria", "BG"),
    ("Bahrain", "BH"),
    ("Burundi", "BI"),
    ("Benin", "BJ"),
    ("Saint Barthélemy", "BL"),
    ("Bermuda", "BM"),
    ("Brunei Darussalam", "BN"),
    ("Bolivia", "BO"),
    ("Brazil", "BR"),
    ("Bahamas", "BS"),
    ("Bhutan", "BT"),
    ("Bouvet Island", "BV"),
    ("Botswana", "BW"),
    ("Belarus", "BY"),
    ("Belize", "BZ"),
    ("Canada", "CA"),
    ("Cocos (keeling) Islands", "CC"),
    ("Congo, The Democratic Republic of The", "CD"),
    ("South Africa", "ZA"),
    ("Zambia", "ZM"),
    ("Morocco", "MA"),
    ("Monaco", "MC"),
    ("Moldova, Republic of", "MD"),
    ("Montenegro", "ME"),
    ("Madagascar", "MG"),
    ("Marshall Islands", "MH"),
    ("Macedonia, The Former Yugoslav Republic of", "MK"),
    ("Mali", "ML"),
    ("Myanmar", "MM"),
    ("Mongolia", "MN"),
    ("Macao", "MO"),
    ("Northern Mariana Islands", "MP"),
    ("Martinique", "MQ"),
    ("Mauritania", "MR"),
    ("Montserrat", "MS"),
    ("Malta", "MT"),
    ("Mauritius", "MU"),
    ("Maldives", "MV"),
    ("Malawi", "MW"),
    ("Mexico", "MX"),
    ("Malaysia", "MY"),
    ("Mozambique", "MZ"),
    ("Namibia", "NA"),
    ("New Caledonia", "NC"),
    ("Niger", "NE"),
    ("Norfolk Island", "NF"),
    ("Nigeria", "NG"),
    ("Libyan Arab Jamahiriya", "LY"),
    ("Nicaragua", "NI"),
    ("Netherlands", "NL"),
    ("Norway", "NO"),
    ("Nepal", "NP"),
    ("Saint Martin", "MF"),
    ("Nauru", "NR"),
    ("Niue", "NU"),
    ("New Zealand", "NZ"),
    ("Oman", "OM"),
    ("Panama", "PA"),
    ("Peru", "PE"),
    ("French Polynesia", "PF"),
    ("Papua New Guinea", "PG"),
    ("Philippines", "PH"),
    ("Pakistan", "PK"),
    ("Poland", "PL"),
    ("Saint Pierre and Miquelon", "PM"),
    ("Pitcairn", "PN"),
    ("Puerto Rico", "PR")
]


def load_country_codes(apps, schema_editor):
    CountryCode = apps.get_model("iss", "CountryCode")
    for country_code in COUNTRY_CODES:
        CountryCode.objects.create(country_name=country_code[0],
                                   iso_country_code=country_code[1])


class Migration(migrations.Migration):

    dependencies = [
        ('iss', '0001_initial')
    ]

    operations = [
        migrations.RunPython(load_country_codes)
    ]
