# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-30 15:52


from django.db import migrations


def load_new_org_types(apps, schema_editor):

    NEW_ORG_TYPES = ["Associate",
                     "Baccalaureate",
                     "Master",
                     "Doctoral/Research"]

    OrganizationType = apps.get_model("iss", "OrganizationType")

    for org_type in NEW_ORG_TYPES:
        OrganizationType.objects.create(name=org_type,
                                        id=org_type)


class Migration(migrations.Migration):

    dependencies = [
        ('iss', '0007_fix_org_countries'),
    ]

    operations = [
        migrations.RunPython(load_new_org_types),
    ]
